name: Send Recruiter Emails

on:
  schedule:
    - cron: '0 5 * * *'  # 9:00 AM IST
  workflow_dispatch:

jobs:
  send-emails:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: echo "No external dependencies"

      - name: Send Emails
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python email_sender.py
